<a href="https://colab.research.google.com/github/CodeName-Cho/Assignment/blob/main/ESAA_YB_%EC%A1%B0%EC%A0%95%EC%9C%A4_1%EC%A3%BC%EC%B0%A8_%EA%B3%BC%EC%A0%9C_%EB%AC%B8%EC%A0%9C_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print("NumPy version:", np.__version__)
np.show_config()

NumPy version: 1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep139863411681952
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    n

#### 3. Create a null vector of size 10 (★☆☆)

In [15]:
num_3 = np.zeros(10)
print(num_3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [23]:
a4 = np.array([1, 2, 3, 4, 5])
num_4 = a4.nbytes
print(f"Memory size of the array: {num_4} bytes")

Memory size of the array: 40 bytes


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
num_5 = np.zeros(10)
num_5[4] = 1
print(num_5)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [11]:
num_6 = np.arange(start=10,stop=50)
print(num_6)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [13]:
num_7 = np.sort(num_6)[::-1]
print(num_7)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [14]:
num_8 = np.arange(start=0,stop=9)
num_8 = num_8.reshape(3,3)
print(num_8)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [66]:
a9 = [1,2,0,0,4,0]
b9 = np.arange(start=0, stop=len(a9))
for i in b9:
  if a9[i] != 0:
    print(a9[i],'의 index는',i)

1 의 index는 0
2 의 index는 1
4 의 index는 4


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [32]:
num_10 = np.zeros(9)
num_10 = num_10.reshape(3,3)
for i in [0,1,2]:
  num_10[i,i] = 1
print(num_10)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [37]:
num_11 = np.random.random((3,3,3))
print(num_11)

[[[0.35584089 0.05596931 0.46193734]
  [0.67850197 0.91376735 0.87335779]
  [0.80857109 0.42569914 0.96525948]]

 [[0.21027733 0.92427746 0.66343133]
  [0.43498317 0.72539531 0.08706772]
  [0.29114388 0.0296396  0.56629343]]

 [[0.21532207 0.96123904 0.82969245]
  [0.21879672 0.54558016 0.63667442]
  [0.03567739 0.40856545 0.6312323 ]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [42]:
num_12 = np.random.random((10,10))
print(num_12)
min_value = np.min(num_12)
max_value = np.max(num_12)
print('min_value:',min_value,'\n','max_value:',max_value)

[[0.49678456 0.43947384 0.93961334 0.24350375 0.95575301 0.66473789
  0.45690571 0.94047649 0.70267761 0.15936743]
 [0.65418641 0.47615506 0.62952267 0.46234089 0.56099408 0.53532505
  0.29042267 0.37149191 0.73959    0.05860127]
 [0.92412919 0.13019382 0.72646917 0.23016952 0.85307253 0.53736981
  0.04914911 0.33702459 0.93998583 0.0692453 ]
 [0.89660125 0.5872067  0.99453865 0.67556035 0.14761745 0.79947574
  0.77746552 0.10494762 0.8504633  0.38641339]
 [0.49575728 0.89364504 0.02804179 0.27611452 0.53442716 0.02133334
  0.77376681 0.40519052 0.67970118 0.97334802]
 [0.84827235 0.48774176 0.10259347 0.66315866 0.95016668 0.98110679
  0.9810443  0.90583149 0.63020415 0.93617494]
 [0.55562951 0.33577422 0.86200433 0.60866808 0.84332623 0.37641759
  0.83094236 0.76289611 0.7155439  0.33535013]
 [0.82057149 0.17113215 0.8133774  0.84799431 0.1276717  0.64953144
  0.19574918 0.19571683 0.31487626 0.28406234]
 [0.56932729 0.84610594 0.91486158 0.44581881 0.73923726 0.98689582
  0.00782144

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [53]:
num_13 = np.random.random(30)
print(num_13)
mean_value = np.mean(num_13)
print('mean_value:',mean_value)

[0.1207763  0.09639144 0.1659422  0.00547132 0.87124709 0.41152127
 0.35474457 0.54838192 0.61198542 0.99734094 0.39385098 0.61360722
 0.35659973 0.07286404 0.61331516 0.27382081 0.90029712 0.93800428
 0.35420925 0.2882462  0.87475024 0.75381358 0.3780972  0.98252062
 0.06257459 0.91144606 0.33216592 0.5600291  0.02897148 0.38323688]
mean_value: 0.47520743029640045


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [61]:
num_14 = np.ones(16)
num_14 = num_14.reshape(4,4)
num_14[1:-1:,1:-1:]=0
print(num_14)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [46]:
0 * np.nan

nan

In [47]:
np.nan == np.nan

False

In [48]:
np.inf > np.nan

False

In [49]:
np.nan - np.nan

nan

In [50]:
np.nan in set([np.nan])

True

In [45]:
0.3 == 0.1*3

False

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [51]:
num_10 = np.zeros(25)
num_10 = num_10.reshape(5,5)
for i in [0,1,2,3]:
  num_10[i+1,i] = i+1
print(num_10)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [57]:
num_17 = np.zeros(64)
num_17 = num_17.reshape(8,8)
num_17[::2,1::2]=1
num_17[1::2,::2]=1
print(num_17)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [68]:
np.unravel_index(100, (6,7,8))

(1, 5, 4)

#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [55]:
num_19 = np.random.random((5,5))
mean_19 = np.mean(num_19)
var_19 = np.var(num_19)
Z = (num_19 - mean_19)/var_19
print(Z)

[[ 2.89694451 -2.63995681  3.01796739 -0.66090745 -4.84335738]
 [-4.84538127 -1.41381125  6.97066866 -1.36487059 -0.27694921]
 [-4.51021367  1.69678567  6.74209225 -4.71729876 -4.7206217 ]
 [ 5.41580377 -2.55488177  0.94394252  4.04144494  0.78335467]
 [-0.92055662  1.2853182   2.61261248 -4.13019006  1.19206146]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [77]:
num_20 = np.dtype([('Red', np.ubyte), ('Green', np.ubyte), ('Blue', np.ubyte), ('Alpha', np.ubyte)])
print(num_20)

[('Red', 'u1'), ('Green', 'u1'), ('Blue', 'u1'), ('Alpha', 'u1')]


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
import numpy as np

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 32. Create a random vector of size 10 and sort it (★★☆)

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [ ]:
# column 1

In [ ]:
# column 2

In [ ]:
# column 3