## ESAA YB 1차과제



1-1,2 생략가능을 뒤늦게 봐서 1-2부터는 생략했습니다.

#### 머신러닝
애플리케이션을 수정하지 않고도 데이터를 기반으로 패턴을 학습 후 결과를 예측하는 알고리즘 기법의 통칭

머신러닝 알고리즘은 데이터를 기반으로 통계적 신뢰도를 강화하고 예측 오류를 최소화하기 위한 다양한 수학적 기법을 적용해 데이터 내 패턴을 스스로 인지하고 신뢰도 있는 예측 결과를 도출함

#### 머신러닝의 분류

**지도학습**
- 분류
- 회귀
- 추천 시스템
- 시각/음성 감지/인지
- 텍스트 분석,NLP

**비지도학습**
- 클러스터링
- 차원 축소
- 강화학습

파이썬과 R 기반의 머신러닝 비교

**R**
R은 통계 전용 프로그램 언어로 다양학 많은 통계 패키지를 보유한 것이 큰 장점

**파이썬**
파이썬은 소리 없이 프로그래밍 세계를 점령하고 있는 언어


## 1-3 넘파이

머신러닝의 주요 알고리즘은 선형대수와 통계 등에 기반한다.

Numerical Python을 의미하는 넘파이는 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지입니다. 루프를 사용하지 않고 대량 데이터의 배열 연산을 가능하게 하므로 빠른 배열 연산 속도를 보장함. 그래서 많은 과학 공학 패키지가 이에 의존하고 있음

넘파이는 저수준 언어 기반의 호환API를 제공하며 배열 기반 연산 뿐 아니라 다양한 데이터 핸들링 기능을 제공.

** 넘파이 ndarray 개요**
as np를 추가해 모듈을 표현해주는 것이 관례

넘파이의 기반 데이터 타입은 ndarray로 이를 통해 다차원 배열을 쉽게 생성 및 연산을 수행이 가능하다.

넘파이 모듈의 임포트

In [2]:
import numpy as np

**넘파이 array() 함수**

넘파이 array() 함수는 파이썬의 리스트와 같은 다양한 인자를 입력받아 ndarray로 변환하는 기능을 수행한다.

**ndarray 배열의 shape 변수**

ndarray의 크기, 즉 행과 열의 수를 튜플 형태로 가지고 있으며 이를 통해 ndarray 배열의 차원까지 알 수 있습니다.

In [3]:
array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1, 2, 3],
                  [2, 3, 4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1, 2, 3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


#### **nd.array**

사용법: ndarray로 변환을 원하는 객체를 인자로 입력하면 ndarray를 반환함

####**ndarray.shape**

ndarray의 차원과 크기를 튜플 형태로 나타내줌

ex) array1의 shape는 (3,)인데 1차원 array로 3개의 데이터를 가지고 있음을 뜻함

(a,b)는 a개의 row, b개의 col로 이루어졌다는 뜻

array1과 array3의 차이점은 둘은 동일한 데이터 건수를 가지고 있지만 array1은 명확하게 1차원임을 (3,)로 표현한 거고 array3는 명확히 row와 col로 이뤄진 2차원 데이터임을 (1,3)으로 표현한 것임

차원의 차수는 이후에 다룰 reshape() 함수를 통하여 변환할 수 있다.

#### **ndarray.ndim**

각 array의 차원을 확인할 수 있다.

In [4]:
print('array1: {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3: 2차원


array() 함수의 인자로는 파이썬의 리스트 객체가 주로 사용된다. 리스트[]는 1차원, 리스트의 리스트[[]]는 2차원과 같은 형태로 배열의 차원과 크기를 쉽게 표현할 수 있다.

### ndarray의 데이터 타입

ndarray내의 데이터값은 숫자,문자,볼 다 가능, 숫자형의 경우 int형, unsigned int형, float형, complex 타입도 제공

데이터 타입은 그 연산의 특성상 같은 데이터 타입만 가능함

즉 한 개의 ndarry 객체에 int와 float는 함께 있을 수 없음

####**dtype**
를 통해 ndarray내의 테이터 타입을 확인할 수 있음

In [5]:
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


리스트: 서로 다른 데이터 타입 가질 수 있음

ndarray: 내부의 데이터 타입은 그 연산 측성상 같은 데이터 타입만 가능하며 서로 다른 데이터 유형이 섞인 리스트를 ndarray로 변경하면 데이터 크기가 더 큰 데이터 타입으로 일괄 적용됨

### ndarray의 데이터 타입 일괄 적용

더 큰 데이터 타입으로 변경

int와 문자열이 섞이면 숫자형이 문자열 값으로 변환

int와 float의 경우에도 둘다 float64형으로 변경됨

In [6]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


#### **astype()**

ndarray 내 데이터값의 타입 변경

astype()에 인자로 원하는 타입을 문자열로 지정(보통 메모리 절약할 때 이용)

In [7]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


## ndarray를 편리하게 생성하기 - arrange, zeros, ones
특정 크기와 차원을 가진 ndarray를 연속값이나 0또는 1로 초기화해 쉽게 생성해야 할 필요가 있는 경우가 발생할 수 있음

이 경우 **arrange(),zeros(),ones()** 를 이용해 쉽게 ndarray를 생성할 수 있음

(주로 테스트용이나 초기화에 사용)

### arange()

표준함수인 range()와 유사한 기능을 함
array를 range()로 표현하는 것
0부터 함수 인자 값 -1까지의 값을 순차적으로 ndarray의 데이터값으로 변환해준다

In [8]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


#### **zeros()**
함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 0으로 채운 해당 shape를 가진 ndarray를 반환한다.

함수 인자로 dtype 인자를 정해주지 않으면 디폴트로 float64형으로 채움

#### **ones**
함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 1로 채운 해당 shape를 가진 ndarray를 반환함.

In [10]:
zero_array = np.zeros((3, 2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### reshape()
reshape() 메서드는 ndarray를 특정 차원 및 크기로 변환한다.

In [15]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array3"\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3"
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


reshape()는 지정된 사이즈로 변경이 불가능하면 오류가 난다.

In [16]:
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

### -1 인자의 사용
-1을 인자로 사용하면 원래 ndarray와 호환되는 새로운 shape으로 변환해준다.

In [17]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1,5)
print('array2 shape:', array2.shape)
array3 = array1.reshape(5,-1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


10개의 1차원 데이터를 고정된 4개의 칼럼을 가진 로우로는 변경할 수 없기에 다음 예제 reshape(-1,4)에선 에러가 발생한다.

In [18]:
array1 = np.arange(10)
array4 = array1.reshape(-1,4)

ValueError: cannot reshape array of size 10 into shape (4)

- -1 인자는 reshape(-1,1)와 같은 형태로 자주 사용된다.
- reshape(-1,1)은 원본 ndarray가 어떤 형태라도 2차원의 1개의 col을 가진 ndarray로 변환됨을 보장한다.
- ndarray는 stack이나 concat으로 결합할 때 각각의 ndarray의 형태를 통일해 유용히 사용된다.
-  ndarray는 **tolist()** 메서드를 이용해 리스트 자료형으로 변경 가능하다


 시각적 편한 이해를 위해 아래는 ndarray를 리스트로 변환해 출력됨



In [26]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


### 넘파이의 ndarray의 데이터 세트 선택하기 = 인덱싱(indexing)

1. 특정한 데이터만 추출
2. 슬라이싱(Slicing)
3. 팬시 인덱싱(Fancy indexing)
4. 불린 인덱싱(Boolean indexing)

### 단일 값 추출
해당하는 위치의 인덱스 값을 [] 안에 입력하면 됩니다.

In [27]:
# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1,stop=10)
print('array1:', array1)
#index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value = array1[2]
print('value;', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value; 3
<class 'numpy.int64'>


In [31]:
print('맨 뒤의 값:', array1[-1], ', 맨뒤에서 두번째 값:', array1[-2])

맨 뒤의 값: 9 , 맨뒤에서 두번째 값: 8


단일 인덱스를 이용해 ndarray 내의 데이터값도 간단히 수정 가능하다.

In [32]:
array1[0] = 9
array1[8] = 0
print('array1:',array1)

array1: [9 2 3 4 5 6 7 8 0]


In [34]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0,0])
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('(row=2, col=2) index 가리키는 값:', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


### **슬라이싱**

':' 기호를 이용해 슬라이싱함

반환값: [시작]~[종료-1]

.

단일 데이터값 추출을 제외하고 슬라이싱, 팬시 인덱싱, 불린 인덱싱으로 추출된 데이터 세트는 모두 ndarray 타입입니다.

슬라이싱 기호인 ':' 사이의 시작, 종료 인덱스는 생략이 가능합니다.
1. 시작 인덱스 생략 -> 처음 인덱스인 0으로 간주
2. 종료 인덱스 생략 -> 마지막 인덱스로 간주
3. 둘다 생략 -> [처음]:[마지막]

In [35]:
array1 = np.arange(start=1,stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


2차원 ndarray에서의 슬라이싱도 비슷한데 콤마로 로우랑 칼럼 지칭하는 것만 다름

In [36]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


2차원 ndarray에서 뒤에 오는 인덱스를 없애면 1차원 ndarray를 반환한다.

In [37]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


### **팬시 인덱싱**
리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식이다.
array2d[[0,1]]은 ((0,:0),(1,:)) 인덱싱이 적용되었다.

In [40]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1], 2]
print('array2d[[0,1],2] => ', array3.tolist())

array4 = array2d[[0,1], 0:2]
print('array2d[[0,1],0:2] => ', array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] => ', array5.tolist())

array2d[[0,1],2] =>  [3, 6]
array2d[[0,1],0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


### **불린 인덱싱**

조건 필터링과 검색을 동시에 할 수 있기 때문에 매우 자주 사용된다.

불린 인덱싱은 ndarray의 인덱스를 지정하는 [] 내에 조건문을 그대로 기재하기만 하면 된다.

In [41]:
array1d = np.arange(start=1, stop=10)
# [] 안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d >5]
print('array1d >5 불린 인덱싱 결과 값:', array3)

array1d >5 불린 인덱싱 결과 값: [6 7 8 9]


넘파이 ndarray 객체에 조건식을 할당하면 아래와 같이 결과가 나온다.

In [42]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

True 값이 있는 위치 인덱스 값으로 자동 변환해 해당하는 인덱스 위치의 데이터만 반환하게 된다.

In [44]:
boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [45]:
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과 :', array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


### 행렬의 정렬 - **sort()와 argsort()**



### **sort()**
- np.sort()

  -> 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬을 반환

- ndarray.sort()

  -> 원 행렬 자체를 정렬한 형태로 변환하며 반환 값은 None이다.

In [48]:
org_array = np.array([3,1,9,5])
print('원본 행렬:', org_array)
# np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 변환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)
# ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 변환된 정렬 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 변환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 변환된 정렬 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


np.sort()나 ndarray.sort() 모두 기본은 오름차순

내림차순으로 정렬하기 위해서는 [::-1]을 적용해야한다.

ex) np.sort()[::-1]

In [49]:
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


행렬이 2차원 이상일 경우에 axis 축 값 설정을 통해 로우, 칼럼 방향으로 정렬을 수행 가능

- axis = 0 => row
- axis = 1 => col

In [51]:
array2d = np.array([[8,12],
                    [7,1]])
sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


### **np.argsort()**
원본 행렬이 정렬되었을 때 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 때 np.argsort()를 이용한며 원본 인덱스를 ndarray 형으로 반환함

In [52]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:',sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


얘도 역시 내림차순으로 정렬 시 np.argsort()[::-1]

In [53]:
org_array = np.array([3,1,9,5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 정렬 시 원본 행렬의 인덱스:',sort_indices_desc)

행렬 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


ndarray는 메타데이터를 못 가져서 실제 값과 그 값이 뜻하는 메타 데이터를 별도의 ndarray로 각각 가져야만 한다

예시)
시험 성적순으로 학생 이름을 출력하고자 하는 상황

In [54]:
name_array = np.array(['John','Mike','Sarah','Kate','Samuel'])
score_array = np.array([78,95,84,98,88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


### 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

#### np.dot() => 행렬 내적(행렬 곱)
행렬 내적은 행렬 곱이며, 두 행렬 A와 B의 내적은 np.dot()을 이용해 계산이 가능하다.

왼쪽 행렬 열개수 오른 행렬 행 개수 같아야 함 (a,b)*(b,c)

In [56]:
A = np.array([[1,2,3],
             [4,5,6]])
B = np.array([[7,8],
              [9,10],
              [11,12]])
dot_product = np.dot(A,B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


### **Transpose**
전치행렬

In [57]:
A = np.array([[1,2],
              [3,4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
