<a href="https://colab.research.google.com/github/CodeName-Cho/Assignment/blob/main/ESAA_YB_Week1_Fri_Session_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print("NumPy version:", np.__version__)
np.show_config()

NumPy version: 1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep139863411681952
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    n

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
num_3 = np.zeros(10)
print(num_3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [4]:
a4 = np.array([1, 2, 3, 4, 5])
num_4 = a4.nbytes
print(f"Memory size of the array: {num_4} bytes")

Memory size of the array: 40 bytes


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [5]:
num_5 = np.zeros(10)
num_5[4] = 1
print(num_5)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [6]:
num_6 = np.arange(start=10,stop=50)
print(num_6)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [7]:
num_7 = np.sort(num_6)[::-1]
print(num_7)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [8]:
num_8 = np.arange(start=0,stop=9)
num_8 = num_8.reshape(3,3)
print(num_8)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [9]:
a9 = [1,2,0,0,4,0]
b9 = np.arange(start=0, stop=len(a9))
for i in b9:
  if a9[i] != 0:
    print(a9[i],'의 index는',i)

1 의 index는 0
2 의 index는 1
4 의 index는 4


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [10]:
num_10 = np.zeros(9)
num_10 = num_10.reshape(3,3)
for i in [0,1,2]:
  num_10[i,i] = 1
print(num_10)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [11]:
num_11 = np.random.random((3,3,3))
print(num_11)

[[[0.1798795  0.06906822 0.08316615]
  [0.35801924 0.79238503 0.34442624]
  [0.58598896 0.46182489 0.28402378]]

 [[0.16769689 0.12590323 0.4675176 ]
  [0.37080326 0.99193766 0.24387009]
  [0.03631313 0.12864    0.26618197]]

 [[0.20414469 0.6122189  0.02829615]
  [0.96288301 0.71849031 0.76864257]
  [0.44238013 0.77120345 0.38776602]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [12]:
num_12 = np.random.random((10,10))
print(num_12)
min_value = np.min(num_12)
max_value = np.max(num_12)
print('min_value:',min_value,'\n','max_value:',max_value)

[[0.55590062 0.145977   0.92763335 0.58261368 0.05538923 0.3308815
  0.5509186  0.35113613 0.60631142 0.72122776]
 [0.16972099 0.94020186 0.36836547 0.85421924 0.01238103 0.87077316
  0.6066627  0.40403663 0.44239064 0.82315807]
 [0.70197383 0.75359708 0.82643851 0.1305099  0.40002675 0.71194967
  0.18591818 0.3692916  0.03734446 0.45903679]
 [0.61105542 0.60570037 0.84004211 0.17774163 0.27734396 0.9328505
  0.27268007 0.93949071 0.24466585 0.94827009]
 [0.38911757 0.19333072 0.75947842 0.43968781 0.83733428 0.82148734
  0.70198841 0.74036005 0.72170621 0.48808678]
 [0.6843911  0.93280862 0.90451539 0.82748787 0.5368989  0.01797712
  0.49400618 0.44894929 0.3925822  0.52648897]
 [0.03097489 0.02706934 0.71049058 0.48555771 0.60923428 0.29401215
  0.55480989 0.72105553 0.55001409 0.14604007]
 [0.35487989 0.00436728 0.77916498 0.25447763 0.22024082 0.49096122
  0.06472279 0.09945539 0.40126273 0.76445524]
 [0.93966734 0.20486425 0.48856247 0.44635437 0.78108798 0.03031633
  0.45751351 0

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [13]:
num_13 = np.random.random(30)
print(num_13)
mean_value = np.mean(num_13)
print('mean_value:',mean_value)

[0.03194425 0.64821056 0.24670886 0.31896769 0.51242906 0.57715464
 0.79636932 0.82344668 0.36660896 0.40639206 0.14767689 0.145009
 0.6622969  0.11768901 0.44107023 0.19029932 0.35587739 0.56074857
 0.89413171 0.08441035 0.69292205 0.01052882 0.29695076 0.47705791
 0.29964608 0.83524807 0.04805176 0.06030065 0.02827398 0.77010689]
mean_value: 0.39488428040611545


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [14]:
num_14 = np.ones(16)
num_14 = num_14.reshape(4,4)
num_14[1:-1:,1:-1:]=0
print(num_14)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [15]:
0 * np.nan

nan

In [16]:
np.nan == np.nan

False

In [17]:
np.inf > np.nan

False

In [18]:
np.nan - np.nan

nan

In [19]:
np.nan in set([np.nan])

True

In [20]:
0.3 == 0.1*3

False

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [21]:
num_10 = np.zeros(25)
num_10 = num_10.reshape(5,5)
for i in [0,1,2,3]:
  num_10[i+1,i] = i+1
print(num_10)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [22]:
num_17 = np.zeros(64)
num_17 = num_17.reshape(8,8)
num_17[::2,1::2]=1
num_17[1::2,::2]=1
print(num_17)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [23]:
np.unravel_index(100, (6,7,8))

(1, 5, 4)

#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [24]:
num_19 = np.random.random((5,5))
mean_19 = np.mean(num_19)
var_19 = np.var(num_19)
Z = (num_19 - mean_19)/var_19
print(Z)

[[-2.40454753  3.63249788  2.92558952  2.80403288 -1.29061019]
 [-3.33707987 -2.76523178 -1.8227948   5.32098367 -0.42902367]
 [-0.59542356  7.61795932 -0.7462179  -4.64250547  0.66302758]
 [-2.29518601 -2.31203673 -4.49617273 -4.74539253 -4.696798  ]
 [ 6.88527877  2.34628317  8.08710632 -5.30703122  1.6032929 ]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [25]:
num_20 = np.dtype([('Red', np.ubyte), ('Green', np.ubyte), ('Blue', np.ubyte), ('Alpha', np.ubyte)])
print(num_20)

[('Red', 'u1'), ('Green', 'u1'), ('Blue', 'u1'), ('Alpha', 'u1')]


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [33]:
matrix_1 = np.array([[1,2,3],
                     [2,3,4],
                     [3,4,5],
                     [4,5,6],
                     [5,6,7]])
matrix_2 = np.array([[9,8],
                    [8,7],
                    [7,6]])

dot_product =np.dot(matrix_1,matrix_2)
print(dot_product)

[[ 46  40]
 [ 70  61]
 [ 94  82]
 [118 103]
 [142 124]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [46]:
num_22 = np.arange(start=1,stop=16)
print(num_22)
num_22 = np.arange(num_22[:2]+num_22[8:])
print(num_22)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


ValueError: operands could not be broadcast together with shapes (2,) (7,) 

#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [34]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [70]:
Z = np.arange(10,dtype=int)
print(Z**Z)

[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]


In [72]:
print(2 << Z >> 2)

[  0   1   2   4   8  16  32  64 128 256]


In [74]:
print(Z <- Z)

[False False False False False False False False False False]


In [77]:
print(1j*Z)

[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]


In [78]:
print(Z/1/1)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [79]:
print(Z<Z>Z)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [81]:
print(np.array(0) / np.array(0))

nan


<ipython-input-81-a69a51a14444>:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))


In [83]:
print(np.array(0) // np.array(0))

0


<ipython-input-83-e29d1dbbd607>:1: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


In [84]:
print(np.array([np.nan]).astype(int).astype(float))

[-9.22337204e+18]


<ipython-input-84-8ac629ca88a6>:1: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [89]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(set(Z1) & set(Z2))

{1, 2, 4, 5, 6, 8}


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [90]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-90-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [92]:
Z = np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [99]:
A = [1,2,3]
B = [5,7,8]

AB_add = np.add(A,B)
# print(AB_add)

Minus_A = np.negative(A)
# print(Minus_A)

Devide_Minus_A_w2 = np.divide(Minus_A , 2)
# print(Devide_Minus_A_w2)

print(np.multiply(AB_add,Devide_Minus_A_w2))

[ -3.   -9.  -16.5]


#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [106]:
A = 23.456

num_30_1 = A//1
print(num_30_1)

num_30_2 = A-A%1
print(num_30_2)

23.0
23.0


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 32. Create a random vector of size 10 and sort it (★★☆)

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [27]:
# column 1

In [28]:
# column 2

In [29]:
# column 3